version: 0.0
os: linux
files:
  - source: target/websocial-1.0-SNAPSHOT.jar
    destination: /opt/tc-social
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 120
      runas: root