version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/websocial-1.0-SNAPSHOT.jar
    - appspec.yml
    - scripts/**/*